# Generated by Django 6.0.3 on 2026-04-04 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_user_profiles(apps, schema_editor):
    """Maneja seed user profiles."""
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")

    roles = [
        ("administrator", "Administradores"),
        ("storekeeper", "Deposito / Panoleros"),
        ("supervisor", "Supervisores"),
        ("operator", "Operarios"),
        ("maintenance", "Mantenimiento"),
        ("purchasing", "Compras"),
        ("auditor", "Auditores"),
    ]
    groups = {}
    for code, name in roles:
        groups[code], _ = Group.objects.get_or_create(name=name)

    for user in User.objects.all():
        role = "administrator" if user.is_superuser else "operator"
        profile, _ = UserProfile.objects.get_or_create(
            user=user,
            defaults={"role": role, "status": "active"},
        )
        groups[profile.role].user_set.add(user)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_category_articlecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrador'), ('storekeeper', 'Deposito / Panolero'), ('supervisor', 'Supervisor'), ('operator', 'Operario'), ('maintenance', 'Mantenimiento'), ('purchasing', 'Compras'), ('auditor', 'Auditor / Consulta')], default='operator', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('sector_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_profiles', to='inventory.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(seed_user_profiles, migrations.RunPython.noop),
    ]
