# Generated by Django 6.0.3 on 2026-04-09 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar_userprofile_phone_and_more'),
        ('inventory', '0008_minimumstockdigestconfig_force_send_next'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAction',
            fields=[
                ('code', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('change', 'Editar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('approve', 'Aprobar')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Acción de Permiso',
                'verbose_name_plural': 'Acciones de Permisos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('code', models.CharField(choices=[('inventory_overview', 'Panel de Inventario'), ('stock_management', 'Gestión de Stock'), ('movements', 'Movimientos'), ('checkouts', 'Retiros'), ('alarms', 'Alarmas'), ('counts', 'Conteos'), ('discrepancies', 'Discrepancias'), ('admin_users', 'Administración de Usuarios'), ('reports', 'Reportes'), ('settings', 'Configuración')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Módulo de Permiso',
                'verbose_name_plural': 'Módulos de Permisos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherit_role_permissions', models.BooleanField(default=True, help_text='Si está marcado, hereda todos los permisos de su rol. Los permisos específicos se suman a los del rol.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrador'), ('storekeeper', 'Deposito / Panolero'), ('supervisor', 'Supervisor'), ('operator', 'Operario'), ('maintenance', 'Mantenimiento'), ('purchasing', 'Compras'), ('auditor', 'Auditor / Consulta')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(help_text='Acciones permitidas en este módulo', related_name='role_permissions', to='accounts.permissionaction')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permissionmodule')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='SectorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='inventory.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Sector',
                'verbose_name_plural': 'Permisos de Sectores',
                'ordering': ['user', 'sector'],
                'unique_together': {('user', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField(default=True, help_text='Si está marcado, permite estas acciones. Si no, las deniega (sobrescribe permiso del rol)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions', models.ManyToManyField(help_text='Acciones permitidas para este usuario en este módulo', related_name='user_module_permissions', to='accounts.permissionaction')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module_permissions', to='accounts.permissionmodule')),
                ('user_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.userpermission')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo del Usuario',
                'verbose_name_plural': 'Permisos de Módulos del Usuario',
                'ordering': ['user_permission', 'module'],
                'unique_together': {('user_permission', 'module')},
            },
        ),
    ]
