# Generated by Django 6.0.3 on 2026-04-16 12:59

from django.db import migrations, models


def seed_deposit_permissions(apps, schema_editor):
    PermissionAction = apps.get_model("accounts", "PermissionAction")
    PermissionModule = apps.get_model("accounts", "PermissionModule")
    RolePermission = apps.get_model("accounts", "RolePermission")
    actions_data = {
        "view": ("Ver", "Permite visualizar"),
        "create": ("Crear", "Permite crear nuevos registros"),
        "change": ("Editar", "Permite editar registros existentes"),
        "delete": ("Eliminar", "Permite eliminar registros"),
    }
    for code, (name, description) in actions_data.items():
        PermissionAction.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )

    modules_data = [
        ("deposits_overview", "Panel de Depósitos", "Vista general del módulo Depósitos", 11),
        ("pallet_registry", "Registro de Pallets", "Alta, consulta y mantenimiento de pallets", 12),
        ("deposit_layout", "Plano de Depósitos", "Visualización y gestión del plano físico", 13),
        ("pallet_scans", "Escaneo de Pallets", "Escaneo QR, lookup y reubicaciones", 14),
    ]
    for code, name, description, order in modules_data:
        PermissionModule.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "order": order,
            },
        )

    role_permissions_config = {
        "administrator": {
            "deposits_overview": ["view"],
            "pallet_registry": ["view", "create", "change", "delete"],
            "deposit_layout": ["view", "create", "change", "delete"],
            "pallet_scans": ["view", "create", "change"],
        },
        "storekeeper": {
            "deposits_overview": ["view"],
            "pallet_registry": ["view", "create", "change", "delete"],
            "deposit_layout": ["view", "create", "change", "delete"],
            "pallet_scans": ["view", "create", "change"],
        },
        "supervisor": {
            "deposits_overview": ["view"],
            "pallet_registry": ["view"],
            "deposit_layout": ["view"],
            "pallet_scans": ["view", "create"],
        },
        "operator": {
            "deposits_overview": ["view"],
            "pallet_registry": ["view"],
            "deposit_layout": ["view"],
            "pallet_scans": ["view", "create"],
        },
        "auditor": {
            "deposits_overview": ["view"],
            "pallet_registry": ["view"],
            "deposit_layout": ["view"],
        },
    }

    for role, modules in role_permissions_config.items():
        for module_code, action_codes in modules.items():
            module = PermissionModule.objects.get(code=module_code)
            role_permission, _ = RolePermission.objects.get_or_create(role=role, module=module)
            role_permission.actions.set(
                PermissionAction.objects.filter(code__in=action_codes)
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_permissionaction_permissionmodule_userpermission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionmodule",
            name="code",
            field=models.CharField(
                choices=[
                    ("inventory_overview", "Panel de Inventario"),
                    ("stock_management", "Gestión de Stock"),
                    ("movements", "Movimientos"),
                    ("checkouts", "Retiros"),
                    ("alarms", "Alarmas"),
                    ("counts", "Conteos"),
                    ("discrepancies", "Discrepancias"),
                    ("admin_users", "Administración de Usuarios"),
                    ("reports", "Reportes"),
                    ("settings", "Configuración"),
                    ("deposits_overview", "Panel de Depósitos"),
                    ("pallet_registry", "Registro de Pallets"),
                    ("deposit_layout", "Plano de Depósitos"),
                    ("pallet_scans", "Escaneo de Pallets"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_deposit_permissions, migrations.RunPython.noop),
    ]
