# Generated by Django 6.0.3 on 2026-04-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permissionmodule_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodule',
            name='code',
            field=models.CharField(choices=[('inventory_overview', 'Panel de Inventario'), ('stock_management', 'Gestión de Stock'), ('movements', 'Movimientos'), ('checkouts', 'Retiros'), ('alarms', 'Alarmas'), ('counts', 'Conteos'), ('discrepancies', 'Discrepancias'), ('admin_users', 'Administración de Usuarios'), ('personal', 'Personal'), ('tia', 'TIA'), ('purchasing', 'Compras'), ('reports', 'Reportes'), ('settings', 'Configuración'), ('deposits_overview', 'Panel de Depósitos'), ('pallet_registry', 'Registro de Pallets'), ('deposit_layout', 'Plano de Depósitos'), ('pallet_scans', 'Escaneo de Pallets')], max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
