from django.urls import path

from .deposits_views import (
    deposits_layout,
    deposits_overview,
    pallet_detail,
    pallet_scan,
    pallets,
)
from .tia_views import tia_ai_reports, tia_mcp_config, tia_mcp_logs, tia_mcp_test, tia_overview
from .views import (
    article_detail,
    article_export_excel,
    article_import_excel,
    articles,
    balances,
    batches,
    catalogs,
    checkout_return,
    checkouts,
    count_session_lines,
    count_sessions,
    dashboard,
    discrepancies,
    discrepancy_resolve,
    inventory_safety_alerts,
    inventory_minimum_stock_digest,
    inventory_full_stock_report,
    inventory_overview,
    inventory_alarms,
    movements,
    personal_daily_report_bulk_delete,
    personal_daily_report_export_excel,
    personal_daily_report_import_excel,
    personal_daily_report_delete,
    personal_daily_report_detail,
    personal_daily_reports,
    tracked_units,
)

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("catalogs/", catalogs, name="catalogs"),
    path("articles/", articles, name="articles"),
    path("articles/export-excel/", article_export_excel, name="article-export-excel"),
    path("articles/import-excel/", article_import_excel, name="article-import-excel"),
    path("articles/<int:article_id>/", article_detail, name="article-detail"),
    path("personal/reports/", personal_daily_reports, name="personal-daily-reports"),
    path(
        "personal/reports/export-excel/",
        personal_daily_report_export_excel,
        name="personal-daily-reports-export-excel",
    ),
    path(
        "personal/reports/<int:report_id>/",
        personal_daily_report_detail,
        name="personal-daily-report-detail",
    ),
    path(
        "personal/reports/<int:report_id>/delete/",
        personal_daily_report_delete,
        name="personal-daily-report-delete",
    ),
    path(
        "personal/reports/bulk-delete/",
        personal_daily_report_bulk_delete,
        name="personal-daily-report-bulk-delete",
    ),
    path(
        "personal/reports/import-excel/",
        personal_daily_report_import_excel,
        name="personal-daily-report-import-excel",
    ),
    path("balances/", balances, name="balances"),
    path("batches/", batches, name="batches"),
    path("tracked-units/", tracked_units, name="tracked-units"),
    path("movements/", movements, name="movements"),
    path("checkouts/", checkouts, name="checkouts"),
    path("checkouts/<int:checkout_id>/return/", checkout_return, name="checkout-return"),
    path("counts/", count_sessions, name="count-sessions"),
    path("counts/<int:session_id>/lines/", count_session_lines, name="count-session-lines"),
    path("discrepancies/", discrepancies, name="discrepancies"),
    path("discrepancies/<int:discrepancy_id>/resolve/", discrepancy_resolve, name="discrepancy-resolve"),
    path("inventory/alarms/", inventory_alarms, name="inventory-alarms"),
    path("inventory/safety-alerts/", inventory_safety_alerts, name="inventory-safety-alerts"),
    path("inventory/minimum-stock-digest/", inventory_minimum_stock_digest, name="inventory-minimum-stock-digest"),
    path("inventory/full-stock-report/", inventory_full_stock_report, name="inventory-full-stock-report"),
    path("inventory/overview/", inventory_overview, name="inventory-overview"),
    path("tia/overview/", tia_overview, name="tia-overview"),
    path("tia/reports/", tia_ai_reports, name="tia-ai-reports"),
    path("tia/mcp/config/", tia_mcp_config, name="tia-mcp-config"),
    path("tia/mcp/test/", tia_mcp_test, name="tia-mcp-test"),
    path("tia/mcp/logs/", tia_mcp_logs, name="tia-mcp-logs"),
    path("deposits/overview/", deposits_overview, name="deposits-overview"),
    path("deposits/layout/<int:location_id>/", deposits_layout, name="deposits-layout"),
    path("pallets/", pallets, name="pallets"),
    path("pallets/<int:pallet_id>/", pallet_detail, name="pallet-detail"),
    path("pallets/scan/", pallet_scan, name="pallet-scan"),
]
