# Generated by Django 6.0.3 on 2026-04-03 23:59

from decimal import Decimal

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_demo_data(apps, schema_editor):
    """Maneja seed demo data."""
    User = apps.get_model("auth", "User")
    InventoryCategory = apps.get_model("inventory", "InventoryCategory")
    InventoryItem = apps.get_model("inventory", "InventoryItem")

    if not User.objects.filter(username="admin").exists():
        User.objects.create(
            username="admin",
            email="admin@inventary.local",
            first_name="Panel",
            last_name="Admin",
            is_staff=True,
            is_superuser=True,
            password=make_password("admin1234"),
        )

    categories = {
        "Insumos": InventoryCategory.objects.get_or_create(
            name="Insumos",
            defaults={
                "description": "Materiales de reposicion rapida",
                "color": "#38a6ff",
            },
        )[0],
        "Electronica": InventoryCategory.objects.get_or_create(
            name="Electronica",
            defaults={
                "description": "Equipos y accesorios",
                "color": "#ea4cb8",
            },
        )[0],
        "Deposito": InventoryCategory.objects.get_or_create(
            name="Deposito",
            defaults={
                "description": "Stock de almacen central",
                "color": "#25c2a0",
            },
        )[0],
    }

    items = [
        {
            "name": "Scanner Zebra DS2208",
            "sku": "INV-001",
            "category": categories["Electronica"],
            "quantity": 4,
            "minimum_stock": 3,
            "unit_price": Decimal("89.90"),
            "location": "Rack A1",
        },
        {
            "name": "Notebook deposito",
            "sku": "INV-002",
            "category": categories["Electronica"],
            "quantity": 2,
            "minimum_stock": 2,
            "unit_price": Decimal("780.00"),
            "location": "Oficina 2",
        },
        {
            "name": "Etiquetas termicas 100x150",
            "sku": "INV-003",
            "category": categories["Insumos"],
            "quantity": 18,
            "minimum_stock": 10,
            "unit_price": Decimal("12.50"),
            "location": "Rack B4",
        },
        {
            "name": "Cinta de embalaje",
            "sku": "INV-004",
            "category": categories["Insumos"],
            "quantity": 6,
            "minimum_stock": 8,
            "unit_price": Decimal("3.25"),
            "location": "Rack B1",
        },
        {
            "name": "Lector RFID",
            "sku": "INV-005",
            "category": categories["Electronica"],
            "quantity": 1,
            "minimum_stock": 2,
            "unit_price": Decimal("155.00"),
            "location": "Rack A3",
        },
        {
            "name": "Caja plastica 60L",
            "sku": "INV-006",
            "category": categories["Deposito"],
            "quantity": 22,
            "minimum_stock": 5,
            "unit_price": Decimal("9.70"),
            "location": "Rack C2",
        },
        {
            "name": "Guantes de seguridad",
            "sku": "INV-007",
            "category": categories["Deposito"],
            "quantity": 0,
            "minimum_stock": 6,
            "unit_price": Decimal("4.90"),
            "location": "Rack C5",
        },
        {
            "name": "Impresora de etiquetas",
            "sku": "INV-008",
            "category": categories["Electronica"],
            "quantity": 3,
            "minimum_stock": 1,
            "unit_price": Decimal("215.00"),
            "location": "Mesa tecnica",
        },
    ]

    for item in items:
        InventoryItem.objects.get_or_create(
            sku=item["sku"],
            defaults=item,
        )


def remove_demo_data(apps, schema_editor):
    """Maneja remove demo data."""
    User = apps.get_model("auth", "User")
    InventoryCategory = apps.get_model("inventory", "InventoryCategory")
    InventoryItem = apps.get_model("inventory", "InventoryItem")

    InventoryItem.objects.filter(
        sku__in=[
            "INV-001",
            "INV-002",
            "INV-003",
            "INV-004",
            "INV-005",
            "INV-006",
            "INV-007",
            "INV-008",
        ]
    ).delete()
    InventoryCategory.objects.filter(
        name__in=["Insumos", "Electronica", "Deposito"]
    ).delete()
    User.objects.filter(username="admin", email="admin@inventary.local").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo_data, remove_demo_data),
    ]
