# Generated by Django 6.0.3 on 2026-04-04 00:56

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def detect_article_type(name, category_name, Article):
    """Maneja detect article type."""
    normalized = (name or "").lower()
    category_name = (category_name or "").lower()

    if any(token in normalized for token in ["scanner", "notebook", "lector", "impresora"]):
        return "tool"
    if "electronica" in category_name:
        return "tool"
    if any(token in normalized for token in ["guante", "casco", "botin", "antiparra", "protector"]):
        return "ppe"
    if any(token in normalized for token in ["caja", "embalaje", "etiqueta", "cinta"]):
        return "consumable"
    return "input"


def migrate_legacy_inventory(apps, schema_editor):
    """Maneja migrate legacy inventory."""
    User = apps.get_model("auth", "User")
    LegacyCategory = apps.get_model("inventory", "InventoryCategory")
    LegacyItem = apps.get_model("inventory", "InventoryItem")
    ArticleCategory = apps.get_model("inventory", "ArticleCategory")
    Article = apps.get_model("inventory", "Article")
    UnitOfMeasure = apps.get_model("inventory", "UnitOfMeasure")
    Sector = apps.get_model("inventory", "Sector")
    Location = apps.get_model("inventory", "Location")
    InventoryBalance = apps.get_model("inventory", "InventoryBalance")
    TrackedUnit = apps.get_model("inventory", "TrackedUnit")
    Person = apps.get_model("inventory", "Person")

    admin_user = User.objects.filter(username="admin").first() or User.objects.order_by("id").first()

    def audit_defaults():
        """Maneja audit defaults."""
        return {"created_by": admin_user, "updated_by": admin_user}

    deposit_sector, _ = Sector.objects.get_or_create(
        name="Deposito",
        defaults={"code": "DEP", "status": "active", **audit_defaults()},
    )
    production_sector, _ = Sector.objects.get_or_create(
        name="Produccion",
        defaults={"code": "PROD", "status": "active", **audit_defaults()},
    )
    maintenance_sector, _ = Sector.objects.get_or_create(
        name="Mantenimiento",
        defaults={"code": "MANT", "status": "active", **audit_defaults()},
    )
    quality_sector, _ = Sector.objects.get_or_create(
        name="Calidad",
        defaults={"code": "CAL", "status": "active", **audit_defaults()},
    )

    default_location, _ = Location.objects.get_or_create(
        code="DEP-PRINCIPAL",
        defaults={
            "name": "Deposito principal",
            "location_type": "warehouse",
            "status": "active",
            "sector": deposit_sector,
            **audit_defaults(),
        },
    )
    Location.objects.get_or_create(
        code="SIN-UBICAR",
        defaults={
            "name": "Sin ubicar",
            "location_type": "other",
            "status": "active",
            "sector": deposit_sector,
            **audit_defaults(),
        },
    )
    Location.objects.get_or_create(
        code="PANOL-001",
        defaults={
            "name": "Panol central",
            "location_type": "toolroom",
            "status": "active",
            "sector": maintenance_sector,
            **audit_defaults(),
        },
    )

    unit_un, _ = UnitOfMeasure.objects.get_or_create(
        code="UN",
        defaults={"name": "Unidad", "status": "active", **audit_defaults()},
    )
    UnitOfMeasure.objects.get_or_create(
        code="PAR",
        defaults={"name": "Par", "status": "active", **audit_defaults()},
    )
    UnitOfMeasure.objects.get_or_create(
        code="KG",
        defaults={"name": "Kilogramo", "status": "active", **audit_defaults()},
    )
    UnitOfMeasure.objects.get_or_create(
        code="L",
        defaults={"name": "Litro", "status": "active", **audit_defaults()},
    )
    UnitOfMeasure.objects.get_or_create(
        code="M",
        defaults={"name": "Metro", "status": "active", **audit_defaults()},
    )

    Person.objects.get_or_create(
        full_name="Juan Perez",
        defaults={
            "status": "active",
            "employee_code": "LEG-001",
            "sector": maintenance_sector,
            "position": "Tecnico de mantenimiento",
            **audit_defaults(),
        },
    )
    Person.objects.get_or_create(
        full_name="Ana Gomez",
        defaults={
            "status": "active",
            "employee_code": "LEG-002",
            "sector": production_sector,
            "position": "Operaria de produccion",
            **audit_defaults(),
        },
    )
    Person.objects.get_or_create(
        full_name="Luis Fernandez",
        defaults={
            "status": "active",
            "employee_code": "LEG-003",
            "sector": quality_sector,
            "position": "Inspector de calidad",
            **audit_defaults(),
        },
    )

    category_map = {}
    for legacy_category in LegacyCategory.objects.all():
        category, _ = ArticleCategory.objects.get_or_create(
            name=legacy_category.name,
            defaults={
                "description": legacy_category.description,
                "status": "active",
                **audit_defaults(),
            },
        )
        category_map[legacy_category.id] = category

    for legacy_item in LegacyItem.objects.all():
        category = category_map.get(legacy_item.category_id)
        article_type = detect_article_type(
            legacy_item.name,
            category.name if category else "",
            Article,
        )
        tracking_mode = "unit" if article_type == "tool" else "quantity"
        minimum_stock = None
        if article_type in {"consumable", "input"}:
            minimum_stock = Decimal(legacy_item.minimum_stock)
        elif article_type == "ppe" and legacy_item.minimum_stock:
            minimum_stock = Decimal(legacy_item.minimum_stock)

        article = Article.objects.create(
            internal_code=legacy_item.sku,
            name=legacy_item.name,
            article_type=article_type,
            unit_of_measure=unit_un,
            status="active" if legacy_item.is_active else "inactive",
            sector_responsible=maintenance_sector if article_type == "tool" else deposit_sector,
            tracking_mode=tracking_mode,
            category=category,
            primary_location=default_location,
            observations=legacy_item.location or "",
            minimum_stock=minimum_stock,
            loanable=article_type == "tool",
            created_by=admin_user,
            updated_by=admin_user,
        )

        if tracking_mode == "quantity":
            InventoryBalance.objects.create(
                article=article,
                location=default_location,
                on_hand=Decimal(legacy_item.quantity),
                reserved=Decimal("0"),
                created_by=admin_user,
                updated_by=admin_user,
            )
        else:
            for index in range(1, legacy_item.quantity + 1):
                TrackedUnit.objects.create(
                    article=article,
                    internal_tag=f"{legacy_item.sku}-{index:03d}",
                    status="available",
                    current_location=default_location,
                    current_sector=maintenance_sector,
                    created_by=admin_user,
                    updated_by=admin_user,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.articlecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de articulo',
                'verbose_name_plural': 'Categorias de articulos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('article_type', models.CharField(choices=[('consumable', 'Consumible'), ('input', 'Insumo productivo'), ('tool', 'Herramienta'), ('spare_part', 'Repuesto'), ('ppe', 'Elemento de proteccion personal')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('discontinued', 'Descontinuado')], default='active', max_length=16)),
                ('tracking_mode', models.CharField(choices=[('quantity', 'Por cantidad'), ('unit', 'Por unidad')], default='quantity', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('safety_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('suggested_purchase_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_purchase', models.DateField(blank=True, null=True)),
                ('requires_lot', models.BooleanField(default=False)),
                ('requires_expiry', models.BooleanField(default=False)),
                ('requires_serial', models.BooleanField(default=False)),
                ('requires_size', models.BooleanField(default=False)),
                ('requires_quality', models.BooleanField(default=False)),
                ('requires_assignee', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('loanable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.articlecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_articles', to='inventory.articlecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=40, unique=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('partial', 'Entrega parcial'), ('closed', 'Cerrada'), ('rejected', 'Rechazada')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_delivered', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_request_lines', to='inventory.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.internalrequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['request', 'article__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('document_ref', models.CharField(blank=True, max_length=120)),
                ('quality_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('quarantine', 'Cuarentena')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['article__name', 'lot_code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location_type', models.CharField(choices=[('warehouse', 'Deposito'), ('toolroom', 'Panol'), ('production', 'Produccion'), ('quality', 'Calidad'), ('quarantine', 'Cuarentena'), ('maintenance', 'Mantenimiento'), ('other', 'Otra')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='inventory.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='inventory.inventorybatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.location')),
            ],
            options={
                'ordering': ['article__name', 'location__name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='primary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('employee_code', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('digital_signature', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='inventory.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_locations', to='inventory.person'),
        ),
        migrations.AddField(
            model_name='internalrequest',
            name='delivery_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_internal_requests', to='inventory.person'),
        ),
        migrations.AddField(
            model_name='internalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requests', to='inventory.person'),
        ),
        migrations.CreateModel(
            name='PhysicalCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_type', models.CharField(choices=[('general', 'General'), ('partial', 'Parcial'), ('sector', 'Por sector'), ('family', 'Por familia'), ('cyclic', 'Ciclico')], max_length=16)),
                ('scope', models.CharField(max_length=120)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('review', 'En revision'), ('closed', 'Cerrado')], default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_sessions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('counted_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('possible_cause', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('approved', 'Aprobado')], default='pending', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_count_lines', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.article')),
                ('counter_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.physicalcountsession')),
            ],
            options={
                'ordering': ['session', 'article__name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='inventory.sector'),
        ),
        migrations.AddField(
            model_name='location',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='inventory.sector'),
        ),
        migrations.AddField(
            model_name='internalrequest',
            name='requesting_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requests', to='inventory.sector'),
        ),
        migrations.AddField(
            model_name='article',
            name='sector_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_articles', to='inventory.sector'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Ingreso por compra'), ('return_in', 'Ingreso por devolucion'), ('adjustment_in', 'Ingreso por ajuste'), ('consumption_out', 'Egreso por consumo'), ('production_out', 'Egreso por produccion'), ('loan_out', 'Egreso por prestamo'), ('damage_out', 'Egreso por rotura'), ('expired_out', 'Egreso por vencimiento'), ('transfer', 'Transferencia'), ('count_adjust', 'Ajuste por inventario'), ('disposal_out', 'Baja definitiva')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason_text', models.CharField(blank=True, max_length=255)),
                ('document_ref', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.article')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_movements', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorybatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.person')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_movements', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.sector')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.location')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difference_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference_type', models.CharField(choices=[('positive', 'Positiva'), ('negative', 'Negativa')], max_length=16)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('possible_cause', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('resolved', 'Resuelta'), ('ignored', 'Ignorada')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='inventory.article')),
                ('count_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='inventory.physicalcountline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='TrackedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_tag', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('checked_out', 'Prestada'), ('in_use', 'En uso'), ('repair', 'En reparacion'), ('out_of_service', 'Fuera de servicio'), ('lost', 'Perdida'), ('retired', 'Dada de baja')], default='available', max_length=24)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('useful_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_revision_at', models.DateField(blank=True, null=True)),
                ('retired_at', models.DateField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_units', to='inventory.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_holder_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_units', to='inventory.person')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_units', to='inventory.location')),
                ('current_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_units', to='inventory.sector')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['internal_tag'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tracked_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.trackedunit'),
        ),
        migrations.CreateModel(
            name='AssetCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkout_kind', models.CharField(choices=[('loan', 'Prestamo'), ('assignment', 'Asignacion')], max_length=16)),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('returned', 'Devuelto'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='open', max_length=16)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_out', models.CharField(blank=True, max_length=120)),
                ('condition_in', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_checkouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_checkouts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('receiver_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_checkouts', to='inventory.person')),
                ('receiver_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_checkouts', to='inventory.sector')),
                ('tracked_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='inventory.trackedunit')),
            ],
            options={
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='inventory.unitofmeasure'),
        ),
        migrations.RunPython(migrate_legacy_inventory, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('article', 'location', 'batch'), name='unique_inventory_balance'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('article', 'location'), name='unique_inventory_balance_without_batch'),
        ),
        migrations.AddConstraint(
            model_name='physicalcountline',
            constraint=models.UniqueConstraint(fields=('session', 'article', 'location'), name='unique_count_line'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('article', 'lot_code'), name='unique_batch_per_article'),
        ),
    ]
