# Generated by Django 6.0.3 on 2026-04-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_safetystockalertrule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MinimumStockDigestConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("frequency", models.CharField(choices=[("daily", "Diario"), ("weekly", "Semanal")], default="daily", max_length=16)),
                ("additional_emails", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_error", models.TextField(blank=True)),
                ("last_summary_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("recipients", models.ManyToManyField(blank=True, related_name="inventory_minimum_stock_digest_configs", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Resumen periodico de stock minimo",
                "verbose_name_plural": "Resumenes periodicos de stock minimo",
                "ordering": ["key"],
            },
        ),
    ]
