# Generated by Django 6.0.3 on 2026-04-07 15:52

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_minimumstockdigestconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='inflight_period_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='inflight_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='last_delivery_status',
            field=models.CharField(choices=[('never', 'Sin ejecuciones'), ('success', 'Enviado'), ('warning', 'Con advertencias'), ('error', 'Error'), ('skipped', 'Sin envio')], default='never', max_length=16),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='last_period_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='last_recipient_warning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='run_at',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='run_weekday',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.CreateModel(
            name='InventoryAutomationTaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=48, unique=True)),
                ('runtime_state', models.CharField(choices=[('idle', 'Inactiva'), ('running', 'En ejecucion'), ('disabled', 'Deshabilitada')], default='idle', max_length=16)),
                ('owner_token', models.CharField(blank=True, max_length=80)),
                ('owner_label', models.CharField(blank=True, max_length=160)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_warning_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('never', 'Sin ejecuciones'), ('success', 'Correcta'), ('warning', 'Con advertencias'), ('error', 'Error'), ('skipped', 'Sin trabajo')], default='never', max_length=16)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_warning_message', models.TextField(blank=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_processed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de automatizacion de inventario',
                'verbose_name_plural': 'Estados de automatizacion de inventario',
                'ordering': ['key'],
            },
        ),
    ]
