# Generated by Django 6.0.3 on 2026-04-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_minimumstockdigestconfig_inflight_period_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimumstockdigestconfig',
            name='force_send_next',
            field=models.BooleanField(default=False, help_text='Marca para forzar el envío en el próximo ciclo (se auto-resetea después)'),
        ),
    ]
