# Generated by Django 6.0.3 on 2026-04-10 00:00

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_minimumstockdigestconfig_force_send_next"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FullStockReportConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(default="default", max_length=32, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("frequency", models.CharField(choices=[("daily", "Diario"), ("weekly", "Semanal")], default="daily", max_length=16)),
                ("run_at", models.TimeField(default=datetime.time(8, 0))),
                ("run_weekday", models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ("additional_emails", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_error", models.TextField(blank=True)),
                ("last_summary_count", models.PositiveIntegerField(blank=True, null=True)),
                ("last_period_key", models.CharField(blank=True, max_length=64)),
                ("inflight_period_key", models.CharField(blank=True, max_length=64)),
                ("inflight_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_delivery_status", models.CharField(choices=[("never", "Sin ejecuciones"), ("success", "Enviado"), ("warning", "Con advertencias"), ("error", "Error"), ("skipped", "Sin envio")], default="never", max_length=16)),
                ("last_recipient_warning", models.TextField(blank=True)),
                ("force_send_next", models.BooleanField(default=False, help_text="Marca para forzar el envío en el próximo ciclo (se auto-resetea después)")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("recipients", models.ManyToManyField(blank=True, related_name="inventory_full_stock_report_configs", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Reporte periodico de stock completo",
                "verbose_name_plural": "Reportes periodicos de stock completo",
                "ordering": ["key"],
            },
        ),
    ]

