# Generated by Django 6.0.3 on 2026-04-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_fullstockreportconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDailyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField()),
                ("day_label", models.CharField(max_length=16)),
                ("activities", models.TextField()),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="personal_daily_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="personaldailyreport",
            constraint=models.UniqueConstraint(fields=("user", "report_date"), name="unique_personal_daily_report"),
        ),
    ]

