# Generated by Django 6.0.3 on 2026-04-16 12:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_storage_layouts(apps, schema_editor):
    Location = apps.get_model("inventory", "Location")
    StorageZone = apps.get_model("inventory", "StorageZone")
    StoragePosition = apps.get_model("inventory", "StoragePosition")

    locations = list(
        Location.objects.filter(status="active", location_type__in=["warehouse", "toolroom"]).order_by("name")
    )
    if not locations:
        fallback = Location.objects.filter(status="active").order_by("name").first()
        if fallback:
            locations = [fallback]

    for location in locations:
        if StorageZone.objects.filter(location=location).exists():
            continue

        zone_specs = [
            {
                "code": "ZA",
                "name": "Zona A",
                "color": "#ffb052",
                "sort_order": 10,
                "positions": [
                    ("A01", 0, 0),
                    ("A02", 2, 0),
                    ("A03", 4, 0),
                    ("A04", 6, 0),
                ],
            },
            {
                "code": "ZB",
                "name": "Zona B",
                "color": "#5fc7ff",
                "sort_order": 20,
                "positions": [
                    ("B01", 0, 2),
                    ("B02", 2, 2),
                    ("B03", 4, 2),
                    ("B04", 6, 2),
                ],
            },
        ]

        for zone_spec in zone_specs:
            zone = StorageZone.objects.create(
                location=location,
                code=zone_spec["code"],
                name=zone_spec["name"],
                color=zone_spec["color"],
                sort_order=zone_spec["sort_order"],
            )
            for code, x, y in zone_spec["positions"]:
                StoragePosition.objects.create(
                    zone=zone,
                    code=code,
                    capacity_pallets=1,
                    x=x,
                    y=y,
                    width=1.8,
                    height=1.2,
                    status="available",
                )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_personaldailyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet_code', models.CharField(max_length=40, unique=True)),
                ('qr_value', models.CharField(max_length=120, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado'), ('moved', 'Movido'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='inventory.article')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='inventory.inventorybatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StoragePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('capacity_pallets', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('x', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('blocked', 'Bloqueada')], default='available', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['zone__location__name', 'zone__sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PalletEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('registered', 'Registrado'), ('relocated', 'Reubicado'), ('scanned_lookup', 'Escaneo de consulta')], max_length=24)),
                ('input_method', models.CharField(choices=[('camera', 'Camara'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('raw_qr', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.pallet')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('source_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_pallet_events', to='inventory.storageposition')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_pallet_events', to='inventory.storageposition')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='inventory.storageposition'),
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location__name', 'sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='storageposition',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='inventory.storagezone'),
        ),
        migrations.AddConstraint(
            model_name='storagezone',
            constraint=models.UniqueConstraint(fields=('location', 'code'), name='unique_storage_zone_per_location'),
        ),
        migrations.AddConstraint(
            model_name='storageposition',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_storage_position_per_zone'),
        ),
        migrations.RunPython(seed_default_storage_layouts, migrations.RunPython.noop),
    ]
