# Generated by Django 6.0.3 on 2026-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_safetystockalertrule_notify_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullstockreportconfig',
            name='last_telegram_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fullstockreportconfig',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fullstockreportconfig',
            name='notify_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
