# Generated by Django 6.0.3 on 2026-04-30 10:17

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_minimum_stock_alarm_config_and_state'),
    ]

    def _ensure_safety_stock_alert_channels(apps, schema_editor):
        """
        Esta migracion repara instalaciones que aplicaron una version anterior de
        0014 que quitaba campos de SafetyStockAlertRule. El estado actual de las
        migraciones ya incluye los campos; aca solo reparamos la base si faltan.
        """
        model = apps.get_model("inventory", "SafetyStockAlertRule")
        table_name = model._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }

        for field_name in ("notify_email", "notify_telegram", "last_telegram_error"):
            try:
                field = model._meta.get_field(field_name)
            except FieldDoesNotExist:
                continue
            if field.column in existing_columns:
                continue
            schema_editor.add_field(model, field)

    operations = [
        migrations.RunPython(_ensure_safety_stock_alert_channels, migrations.RunPython.noop),
    ]
