# Generated by Django 6.0.3 on 2026-05-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_pallet_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='person',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
