# Generated by Django 6.0.3 on 2026-05-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_person_position_signature_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='employee_code',
            new_name='dni',
        ),
    ]
